import { expect, test } from "@playwright/test";
import { freshWorkspace, mockApi } from "./helpers";
import { sel, T } from "./testids";

const fixture = {
  input: {
    hypothesis: "The Strait of Hormuz closes to commercial tanker traffic",
    mode: "explore",
    target: null,
    horizonDays: 90,
    positions: [],
  },
  llm: {
    nodes: 0,
    edges: 0,
    summary: {
      headline: "Closure repricing runs through insurance and OPEC's response",
      mainUncertainty: "Whether spare capacity can be physically rerouted",
      followUps: ["Tanker day rates", "SPR release size"],
    },
  },
  graph: {
    nodes: [
      {
        id: "hormuz-closes",
        kind: "event",
        statement: "The Strait of Hormuz closes to commercial tanker traffic",
        resolution: "Lloyd's List reports a full closure lasting over 48 hours",
        base: 0.08,
        lagDays: [0, 3],
        rationale: "Root hypothesis under test",
        analogs: ["1984 tanker war"],
        assumptions: ["No immediate naval escort deal"],
        confidence: "medium",
        marketQuery: "Strait of Hormuz closure 2026",
        isRoot: true,
        isTarget: false,
      },
      {
        id: "insurance-spike",
        kind: "event",
        statement: "War-risk insurance for Gulf transits doubles",
        resolution: "Lloyd's war-risk premium above 2% of hull value",
        base: 0.2,
        lagDays: [1, 5],
        rationale: "Underwriters reprice within days of a closure",
        analogs: [],
        assumptions: ["Underwriters do not withdraw entirely"],
        confidence: "high",
        marketQuery: "gulf war risk insurance premium",
        isRoot: false,
        isTarget: false,
      },
      {
        id: "opec-release",
        kind: "event",
        statement: "OPEC+ announces an emergency spare-capacity release",
        resolution: "OPEC+ communique naming additional barrels",
        base: 0.25,
        lagDays: [3, 14],
        rationale: "Political pressure to cap the price spike",
        analogs: ["2022 SPR release"],
        assumptions: ["Spare capacity is physically deliverable"],
        confidence: "low",
        marketQuery: "OPEC emergency production increase",
        isRoot: false,
        isTarget: false,
      },
      {
        id: "brent-above-100",
        kind: "event",
        statement: "Brent settles above $100 within the horizon",
        resolution: "ICE Brent front-month settlement above 100",
        base: 0.12,
        lagDays: [2, 20],
        rationale: "Target of the chain",
        analogs: [],
        assumptions: [],
        confidence: "medium",
        marketQuery: "Brent above 100 in 2026",
        isRoot: false,
        isTarget: true,
      },
      {
        id: "tanker-security",
        kind: "event",
        statement: "Regional naval security posture remains elevated",
        resolution: "Navy issues a no-sail warning",
        base: 0.33,
        lagDays: [1, 4],
        rationale: "Security uncertainty raises perceived disruption risk",
        analogs: ["2008 anti-piracy operations"],
        assumptions: ["No immediate de-escalation mechanism"],
        confidence: "medium",
        marketQuery: "Hormuz naval security warning",
        isRoot: false,
        isTarget: false,
      },
      {
        id: "brent",
        kind: "numeric",
        name: "Brent crude",
        unit: "USD/bbl",
        ticker: "BZ=F",
        current: 72.4,
        baselineMove: 0,
        sigma: 14,
        rationale: "Front-month contract",
        assumptions: [],
        confidence: "high",
      },
      {
        id: "airline-index",
        kind: "numeric",
        name: "US airline index",
        unit: "index",
        ticker: "JETS",
        current: 24.1,
        baselineMove: 0,
        sigma: 9,
        rationale: "Fuel is the largest variable cost",
        assumptions: [],
        confidence: "medium",
      },
      {
        id: "shipping-fright",
        kind: "numeric",
        name: "Freight freight rate",
        unit: "$/teu",
        ticker: null,
        current: 2200,
        baselineMove: 0,
        sigma: 18,
        rationale: "Disruption increases transit frictions",
        assumptions: [],
        confidence: "low",
      },
    ],
    edges: [
      {
        id: "e-hormuz-insurance",
        source: "hormuz-closes",
        target: "insurance-spike",
        kind: "ee",
        mechanism: "Closure forces underwriters to reprice",
        assumptions: [],
        confidence: "medium",
        sourceIds: [],
        polarity: "promote",
        strength: 0.85,
        impact: null,
        beta: null,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-hormuz-opec",
        source: "hormuz-closes",
        target: "opec-release",
        kind: "ee",
        mechanism: "A supply shock invites a political response",
        assumptions: [],
        confidence: "medium",
        sourceIds: [],
        polarity: "promote",
        strength: 0.5,
        impact: null,
        beta: null,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-hormuz-brent",
        source: "hormuz-closes",
        target: "brent",
        kind: "en",
        mechanism: "Roughly a fifth of seaborne crude stops moving",
        assumptions: [],
        confidence: "medium",
        sourceIds: [],
        polarity: null,
        strength: null,
        impact: 38,
        beta: null,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-hormuz-security",
        source: "hormuz-closes",
        target: "tanker-security",
        kind: "ee",
        mechanism: "Higher risk of attacks reinforces operational delay",
        assumptions: [],
        confidence: "high",
        sourceIds: [],
        polarity: "promote",
        strength: 0.45,
        impact: null,
        beta: null,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-insurance-brent",
        source: "insurance-spike",
        target: "brent",
        kind: "en",
        mechanism: "Freight cost passes into the landed price",
        assumptions: [],
        confidence: "medium",
        sourceIds: [],
        polarity: null,
        strength: null,
        impact: 6,
        beta: null,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-opec-brent",
        source: "opec-release",
        target: "brent",
        kind: "en",
        mechanism: "Extra barrels cap the spike",
        assumptions: [],
        confidence: "medium",
        sourceIds: [],
        polarity: null,
        strength: null,
        impact: -9,
        beta: null,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-brent-airlines",
        source: "brent",
        target: "airline-index",
        kind: "nn",
        mechanism: "Jet fuel tracks crude",
        assumptions: [],
        confidence: "low",
        sourceIds: [],
        polarity: null,
        strength: null,
        impact: null,
        beta: -0.6,
        threshold: null,
        direction: null,
        width: null,
      },
      {
        id: "e-brent-above",
        source: "brent",
        target: "brent-above-100",
        kind: "ne",
        mechanism: "Level crosses the strike",
        assumptions: [],
        confidence: "high",
        sourceIds: [],
        polarity: null,
        strength: null,
        impact: null,
        beta: null,
        threshold: 100,
        direction: "above",
        width: 8,
      },
    ],
    summary: {
      headline: "Closure repricing runs through insurance and OPEC's response",
      mainUncertainty: "Whether spare capacity can be physically rerouted",
      followUps: ["Tanker day rates", "SPR release size"],
    },
  },
  markets: {
    "hormuz-closes": [
      {
        title: "Will the Strait of Hormuz close to tanker traffic in 2026?",
        url: "https://polymarket.com/event/hormuz-2026",
        yes: 0.275,
        volume: 1_250_000,
        endDate: "2026-12-31",
        source: "polymarket",
      },
    ],
  },
  quotes: {
    "BZ=F": {
      symbol: "BZ=F",
      price: 72.4,
      changePct: 0.8,
      currency: "USD",
      time: "2026-09-01T00:00:00.000Z",
    },
    JETS: {
      symbol: "JETS",
      price: 24.1,
      changePct: -0.4,
      currency: "USD",
      time: "2026-09-01T00:00:00.000Z",
    },
  },
};

test("fixture chip loads a full graph and keeps disclaimer visible", async ({ page }) => {
  await freshWorkspace(page);
  await mockApi(page);

  await page.route("**/fixtures/hormuz.json", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json; charset=utf-8",
      body: JSON.stringify(fixture),
    });
  });

  await page.goto("/");

  const chip = page.locator(sel(T.exampleChip("hormuz")));
  await expect(chip).toBeVisible();
  await chip.click();

  await expect(page.locator(sel(T.canvas))).toBeVisible();
  await expect(page.locator(sel(T.disclaimer))).toBeVisible();

  for (const id of [
    "hormuz-closes",
    "insurance-spike",
    "opec-release",
    "brent-above-100",
    "tanker-security",
    "brent",
    "airline-index",
    "shipping-fright",
  ]) {
    await expect(page.locator(sel(T.node(id)))).toBeVisible();
  }
});
