import { LlmGraph } from "@/lib/schema";
import type { z } from "zod";

type LlmEdge = z.infer<typeof LlmGraph>["edges"][number];

const edge = (
  source: string,
  target: string,
  mechanism: string,
  options: Partial<Omit<LlmEdge, "source" | "target" | "mechanism">> = {},
): LlmEdge => ({
  source,
  target,
  mechanism,
  assumptions: options.assumptions ?? [],
  confidence: options.confidence ?? "medium",
  sourceIds: options.sourceIds ?? [],
  polarity: options.polarity ?? null,
  strength: options.strength ?? null,
  impact: options.impact ?? null,
  beta: options.beta ?? null,
  threshold: options.threshold ?? null,
  direction: options.direction ?? null,
  width: options.width ?? null,
});

export const seed: z.infer<typeof LlmGraph> = {
  nodes: [
    {
      id: "legacy-controls-expand",
      kind: "event",
      statement: "The United States extends semiconductor export controls to selected legacy-node equipment",
      resolution: "Commerce publishes a rule adding defined legacy-node equipment to licensing controls",
      base: 0.34,
      lagDays: [20, 90],
      rationale: "Policy pressure has shifted from frontier AI chips toward the equipment stack that supports military and industrial demand.",
      analogs: ["2022 and 2023 BIS semiconductor rules"],
      assumptions: ["The rule covers meaningful tool categories rather than a symbolic list"],
      confidence: "medium",
      marketQuery: "US legacy semiconductor export controls 2026",
      isRoot: true,
      isTarget: false,
    },
    {
      id: "china-retaliation",
      kind: "event",
      statement: "China responds with procurement guidance favoring domestic semiconductor suppliers",
      resolution: "A central or provincial procurement notice specifies domestic-sourcing preferences",
      base: 0.42,
      lagDays: [15, 75],
      rationale: "Procurement restrictions are easier to implement than an immediate broad export ban.",
      analogs: ["China critical-minerals export controls"],
      assumptions: ["Domestic suppliers can meet minimum qualification thresholds"],
      confidence: "medium",
      marketQuery: "China domestic semiconductor procurement guidance",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "inventory-build",
      kind: "event",
      statement: "Affected Chinese fabs pull forward equipment and spare-parts orders",
      resolution: "Supplier commentary reports order acceleration from affected Chinese customers",
      base: 0.31,
      lagDays: [5, 35],
      rationale: "Customers often build buffer inventory ahead of licensing uncertainty.",
      analogs: ["2020 Huawei supply-chain pull-forward"],
      assumptions: ["Suppliers can ship before the effective date"],
      confidence: "high",
      marketQuery: "China semiconductor equipment inventory pull forward",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "foundry-capex-slowdown",
      kind: "event",
      statement: "Affected foundries defer part of 2027 capacity expansion",
      resolution: "Capex guidance is cut by at least 5 percent versus the prior plan",
      base: 0.38,
      lagDays: [60, 180],
      rationale: "Restricted tools and uncertain end demand can delay marginal fab projects.",
      analogs: ["2019 memory capex cuts"],
      assumptions: ["Financing and local subsidies do not fully offset the restriction"],
      confidence: "medium",
      marketQuery: "China foundry capex reduction 2027",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "allied-exemption",
      kind: "event",
      statement: "Allied fabs receive a narrow licensing exemption for existing facilities",
      resolution: "A Commerce clarification grants case-by-case licenses for named allied facilities",
      base: 0.35,
      lagDays: [20, 100],
      rationale: "An exemption can protect allied supply chains without removing leverage over Chinese expansion.",
      analogs: ["Validated end-user licensing arrangements"],
      assumptions: ["Allies accept reporting conditions"],
      confidence: "low",
      marketQuery: "semiconductor export control allied licensing exemption",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "tool-vendor-guidance-cut",
      kind: "event",
      statement: "Equipment vendors reduce China revenue guidance",
      resolution: "A major equipment vendor cuts China revenue guidance by more than 5 percent",
      base: 0.29,
      lagDays: [45, 150],
      rationale: "Licensing uncertainty hits service and spare-parts revenue before new tool orders are formally canceled.",
      analogs: ["2022 equipment-vendor China guidance revisions"],
      assumptions: ["China remains a material share of revenue"],
      confidence: "medium",
      marketQuery: "semiconductor equipment vendor China revenue guidance cut",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "semiconductor-etf",
      kind: "numeric",
      name: "VanEck Semiconductor ETF",
      unit: "USD/share",
      ticker: "SMH",
      current: 260,
      baselineMove: 0,
      sigma: 20,
      rationale: "The ETF captures equipment, logic, and memory exposure while diversifying company-specific effects.",
      assumptions: ["AI demand remains a partial offset to China weakness"],
      confidence: "high",
    },
    {
      id: "tsmc-adr",
      kind: "numeric",
      name: "Taiwan Semiconductor ADR",
      unit: "USD/share",
      ticker: "TSM",
      current: 210,
      baselineMove: 0,
      sigma: 18,
      rationale: "TSMC is sensitive to both broader semiconductor risk appetite and demand from the China supply chain.",
      assumptions: ["Leading-edge demand stays resilient"],
      confidence: "high",
    },
  ],
  edges: [
    edge("legacy-controls-expand", "china-retaliation", "New restrictions increase the incentive for procurement retaliation", {
      polarity: "promote",
      strength: 0.52,
    }),
    edge("legacy-controls-expand", "inventory-build", "Fabs pull forward purchases before licensing uncertainty bites", {
      polarity: "promote",
      strength: 0.68,
      confidence: "high",
    }),
    edge("legacy-controls-expand", "foundry-capex-slowdown", "Tool uncertainty delays marginal capacity projects", {
      polarity: "promote",
      strength: 0.55,
    }),
    edge("legacy-controls-expand", "allied-exemption", "Supply-chain risk creates pressure for narrow allied licenses", {
      polarity: "promote",
      strength: 0.4,
    }),
    edge("china-retaliation", "tool-vendor-guidance-cut", "Domestic procurement preference reduces addressable demand", {
      polarity: "promote",
      strength: 0.46,
    }),
    edge("allied-exemption", "inventory-build", "A clear exemption reduces the need for precautionary orders", {
      polarity: "inhibit",
      strength: 0.45,
    }),
    edge("inventory-build", "semiconductor-etf", "Near-term pull-forward temporarily supports equipment revenue", {
      impact: 3,
    }),
    edge("foundry-capex-slowdown", "semiconductor-etf", "Deferred capacity lowers equipment and materials demand", {
      impact: -7,
    }),
    edge("tool-vendor-guidance-cut", "semiconductor-etf", "Lower China guidance reprices equipment earnings", {
      impact: -5,
    }),
    edge("allied-exemption", "semiconductor-etf", "A narrow carve-out limits the downside to global supply chains", {
      impact: 2.5,
    }),
    edge("semiconductor-etf", "tsmc-adr", "Sector risk appetite transmits into the leading foundry valuation", {
      beta: 0.78,
    }),
  ],
  summary: {
    headline: "Legacy-node controls create a short inventory pull-forward but a larger medium-term capex and vendor-guidance risk.",
    mainUncertainty: "How broadly the rule defines controlled equipment and whether allied licenses arrive quickly.",
    followUps: ["BIS rule text", "Equipment-vendor China bookings", "Foundry capex guidance"],
  },
};
