import { LlmGraph } from "@/lib/schema";
import type { z } from "zod";

type LlmEdge = z.infer<typeof LlmGraph>["edges"][number];

const edge = (
  source: string,
  target: string,
  mechanism: string,
  options: Partial<Omit<LlmEdge, "source" | "target" | "mechanism">> = {},
): LlmEdge => ({
  source,
  target,
  mechanism,
  assumptions: options.assumptions ?? [],
  confidence: options.confidence ?? "medium",
  sourceIds: options.sourceIds ?? [],
  polarity: options.polarity ?? null,
  strength: options.strength ?? null,
  impact: options.impact ?? null,
  beta: options.beta ?? null,
  threshold: options.threshold ?? null,
  direction: options.direction ?? null,
  width: options.width ?? null,
});

export const seed: z.infer<typeof LlmGraph> = {
  nodes: [
    {
      id: "hormuz-closure",
      kind: "event",
      statement: "The Strait of Hormuz closes to commercial tanker traffic",
      resolution: "Lloyd's List reports a closure lasting more than 48 hours",
      base: 0.08,
      lagDays: [0, 3],
      rationale: "A closure disrupts roughly a fifth of seaborne oil flows before buyers can reroute.",
      analogs: ["1984 tanker war", "2019 Abqaiq disruption"],
      assumptions: ["Naval deterrence does not prevent an initial closure"],
      confidence: "medium",
      marketQuery: "Strait of Hormuz closure tanker traffic 2026",
      isRoot: true,
      isTarget: false,
    },
    {
      id: "war-risk-premium",
      kind: "event",
      statement: "War-risk insurance for Gulf transits doubles",
      resolution: "Quoted war-risk premium exceeds 2% of hull value",
      base: 0.24,
      lagDays: [1, 5],
      rationale: "Underwriters reprice quickly when vessels cannot assess the security of a transit.",
      analogs: ["1980s Persian Gulf war-risk market"],
      assumptions: ["Insurers continue writing cover rather than withdrawing entirely"],
      confidence: "high",
      marketQuery: "Gulf war risk insurance premium tanker",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "opec-spare-capacity-release",
      kind: "event",
      statement: "OPEC+ announces an emergency spare-capacity release",
      resolution: "A ministerial statement names additional barrels available within 30 days",
      base: 0.22,
      lagDays: [3, 14],
      rationale: "Producer governments have a strong incentive to limit a price shock but physical delivery is constrained.",
      analogs: ["2022 coordinated SPR release"],
      assumptions: ["Saudi spare capacity can reach export terminals"],
      confidence: "medium",
      marketQuery: "OPEC emergency spare capacity release",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "naval-escort-deal",
      kind: "event",
      statement: "A credible naval escort arrangement restores escorted tanker transits",
      resolution: "Major insurers accept escorted passages through the strait",
      base: 0.28,
      lagDays: [2, 10],
      rationale: "A negotiated escort channel can reduce the effective supply outage before a full diplomatic settlement.",
      analogs: ["Operation Earnest Will"],
      assumptions: ["Escorts are acceptable to coastal states"],
      confidence: "low",
      marketQuery: "Hormuz naval escort agreement",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "tanker-diversion",
      kind: "event",
      statement: "Asian refiners bid for replacement barrels outside the Gulf",
      resolution: "Spot differentials for Atlantic Basin crude widen for five trading days",
      base: 0.45,
      lagDays: [2, 12],
      rationale: "Refiners can switch marginal barrels, but freight and grade constraints make the response expensive.",
      analogs: ["2022 Russian crude rerouting"],
      assumptions: ["Atlantic Basin exporters have prompt cargo availability"],
      confidence: "medium",
      marketQuery: "Asian refiners replacement crude spot differentials",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "brent-above-100",
      kind: "event",
      statement: "Brent settles above 100 dollars per barrel within the horizon",
      resolution: "ICE Brent front-month settlement exceeds 100 dollars",
      base: 0.12,
      lagDays: [2, 25],
      rationale: "The option-like threshold concentrates the market consequence of the supply interruption.",
      analogs: ["2022 Brent price spike"],
      assumptions: ["Demand destruction remains limited during the first month"],
      confidence: "medium",
      marketQuery: "Brent above 100 2026",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "brent",
      kind: "numeric",
      name: "Brent crude",
      unit: "USD/bbl",
      ticker: "BZ=F",
      current: 72.4,
      baselineMove: 0,
      sigma: 14,
      rationale: "Front-month Brent is the liquid benchmark for the immediate physical supply shock.",
      assumptions: ["The futures curve remains a usable signal of prompt scarcity"],
      confidence: "high",
    },
    {
      id: "airline-etf",
      kind: "numeric",
      name: "US Global Jets ETF",
      unit: "USD/share",
      ticker: "JETS",
      current: 24.1,
      baselineMove: 0,
      sigma: 9,
      rationale: "Airline margins respond negatively to jet-fuel costs before fares can reset.",
      assumptions: ["Fuel hedges do not fully offset a rapid crude move"],
      confidence: "medium",
    },
  ],
  edges: [
    edge("hormuz-closure", "war-risk-premium", "A closure forces underwriters to reprice a transit", {
      polarity: "promote",
      strength: 0.8,
      confidence: "high",
      assumptions: ["Reported incidents are sufficient for an actuarial response"],
    }),
    edge("hormuz-closure", "opec-spare-capacity-release", "The disruption creates political pressure for a supply response", {
      polarity: "promote",
      strength: 0.58,
    }),
    edge("hormuz-closure", "naval-escort-deal", "A closure makes an escorted corridor politically urgent", {
      polarity: "promote",
      strength: 0.55,
    }),
    edge("hormuz-closure", "tanker-diversion", "Lost Gulf barrels force refiners to seek substitute cargoes", {
      polarity: "promote",
      strength: 0.72,
    }),
    edge("hormuz-closure", "brent", "Interrupted seaborne supply reprices prompt crude", {
      impact: 32,
      assumptions: ["The disruption removes at least several million barrels per day"],
      confidence: "high",
    }),
    edge("war-risk-premium", "brent", "Higher freight and insurance costs raise landed crude prices", {
      impact: 8,
    }),
    edge("opec-spare-capacity-release", "brent", "Additional prompt barrels cap the price spike", {
      impact: -10,
    }),
    edge("tanker-diversion", "brent", "Competition for replacement cargoes widens spot differentials", {
      impact: 5,
    }),
    edge("brent", "brent-above-100", "The benchmark reaches the threshold price", {
      threshold: 100,
      direction: "above",
      width: 8,
      strength: 0.75,
    }),
    edge("naval-escort-deal", "brent-above-100", "Restored escorted transits reduce the duration of the shock", {
      polarity: "inhibit",
      strength: 0.6,
    }),
    edge("brent", "airline-etf", "Jet fuel costs compress airline margins", {
      beta: -0.65,
    }),
  ],
  summary: {
    headline: "A Hormuz closure feeds through insurance and replacement barrels before an OPEC or escort response can cap it.",
    mainUncertainty: "Whether an escort corridor restores enough physical flow before inventories tighten.",
    followUps: ["War-risk premium quotes", "Saudi export loading schedules", "Asian refinery spot tenders"],
  },
};
