import { LlmGraph } from "@/lib/schema";
import type { z } from "zod";

type LlmEdge = z.infer<typeof LlmGraph>["edges"][number];

const edge = (
  source: string,
  target: string,
  mechanism: string,
  options: Partial<Omit<LlmEdge, "source" | "target" | "mechanism">> = {},
): LlmEdge => ({
  source,
  target,
  mechanism,
  assumptions: options.assumptions ?? [],
  confidence: options.confidence ?? "medium",
  sourceIds: options.sourceIds ?? [],
  polarity: options.polarity ?? null,
  strength: options.strength ?? null,
  impact: options.impact ?? null,
  beta: options.beta ?? null,
  threshold: options.threshold ?? null,
  direction: options.direction ?? null,
  width: options.width ?? null,
});

export const seed: z.infer<typeof LlmGraph> = {
  nodes: [
    {
      id: "democrats-take-house",
      kind: "event",
      statement: "Democrats win a House majority in the 2026 midterms",
      resolution: "Associated Press calls enough House races for a Democratic majority",
      base: 0.48,
      lagDays: [60, 90],
      rationale: "A narrow national environment makes turnout and a small number of suburban districts decisive.",
      analogs: ["2018 House midterm", "2022 House midterm"],
      assumptions: ["The number of competitive districts remains near current estimates"],
      confidence: "medium",
      marketQuery: "Democrats win House 2026 midterms",
      isRoot: true,
      isTarget: false,
    },
    {
      id: "suburban-turnout",
      kind: "event",
      statement: "Suburban turnout exceeds 2022 levels in competitive districts",
      resolution: "Certified turnout in targeted suburban counties exceeds the 2022 share",
      base: 0.52,
      lagDays: [30, 90],
      rationale: "College-educated suburban turnout has been the most consistent margin driver in close House races.",
      analogs: ["2018 suburban turnout surge"],
      assumptions: ["Turnout operations remain funded through Election Day"],
      confidence: "medium",
      marketQuery: "2026 suburban voter turnout House districts",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "soft-landing",
      kind: "event",
      statement: "Unemployment remains below 4.5 percent into the election",
      resolution: "The October employment report shows unemployment below 4.5 percent",
      base: 0.58,
      lagDays: [30, 85],
      rationale: "A stable labor market reduces the penalty typically borne by the incumbent party.",
      analogs: ["1998 and 2022 midterm labor markets"],
      assumptions: ["A recession does not begin before October"],
      confidence: "medium",
      marketQuery: "US unemployment October 2026 forecast",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "candidate-recruitment",
      kind: "event",
      statement: "Democrats field credible candidates in most open suburban seats",
      resolution: "Party filings show candidates with prior elected or military experience in targeted seats",
      base: 0.62,
      lagDays: [0, 45],
      rationale: "Candidate quality matters disproportionately where partisan registration is nearly balanced.",
      analogs: ["2018 candidate recruitment cycle"],
      assumptions: ["Primary contests do not nominate unelectable outliers"],
      confidence: "medium",
      marketQuery: "Democratic candidate recruitment 2026 House",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "inflation-reacceleration",
      kind: "event",
      statement: "Headline inflation reaccelerates above 3.5 percent before Election Day",
      resolution: "Three-month annualized headline CPI exceeds 3.5 percent",
      base: 0.25,
      lagDays: [20, 80],
      rationale: "A visible cost-of-living shock changes the retrospective economic vote faster than policy messaging can.",
      analogs: ["2022 inflation shock"],
      assumptions: ["Energy and shelter inflation rise together"],
      confidence: "medium",
      marketQuery: "US CPI inflation above 3.5 2026",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "health-policy-agenda",
      kind: "event",
      statement: "A Democratic House prioritizes drug-pricing oversight hearings",
      resolution: "The incoming committee agenda lists drug-pricing oversight as a first-quarter priority",
      base: 0.5,
      lagDays: [65, 90],
      rationale: "A majority shift changes committee subpoena and hearing priorities even without Senate control.",
      analogs: ["2019 House oversight agenda"],
      assumptions: ["Leadership assigns health policy to a high-profile committee"],
      confidence: "medium",
      marketQuery: "Democratic House drug pricing oversight 2027",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "sp500",
      kind: "numeric",
      name: "S&P 500 ETF",
      unit: "USD/share",
      ticker: "SPY",
      current: 610,
      baselineMove: 0,
      sigma: 12,
      rationale: "The broad index reflects the macro outcome more than a single congressional result.",
      assumptions: ["Monetary policy remains the dominant market driver"],
      confidence: "high",
    },
    {
      id: "healthcare-etf",
      kind: "numeric",
      name: "Health Care Select Sector SPDR",
      unit: "USD/share",
      ticker: "XLV",
      current: 150,
      baselineMove: 0,
      sigma: 10,
      rationale: "Managed-care and pharma valuations are sensitive to oversight and reimbursement headlines.",
      assumptions: ["Sector earnings remain otherwise on guidance"],
      confidence: "medium",
    },
  ],
  edges: [
    edge("suburban-turnout", "democrats-take-house", "Higher participation improves margins in marginal suburban districts", {
      polarity: "promote",
      strength: 0.58,
    }),
    edge("soft-landing", "democrats-take-house", "A stable labor market limits the incumbent-party economic penalty", {
      polarity: "promote",
      strength: 0.34,
    }),
    edge("candidate-recruitment", "democrats-take-house", "Stronger challengers convert national sentiment into individual-seat wins", {
      polarity: "promote",
      strength: 0.42,
    }),
    edge("inflation-reacceleration", "democrats-take-house", "A renewed inflation shock weakens the incumbent economic case", {
      polarity: "inhibit",
      strength: 0.56,
      confidence: "high",
    }),
    edge("democrats-take-house", "health-policy-agenda", "Committee control sets the oversight calendar", {
      polarity: "promote",
      strength: 0.72,
    }),
    edge("soft-landing", "sp500", "A stable employment backdrop supports earnings multiples", {
      impact: 4,
    }),
    edge("inflation-reacceleration", "sp500", "Higher inflation raises discount-rate and margin concerns", {
      impact: -6,
    }),
    edge("democrats-take-house", "healthcare-etf", "Oversight risk modestly discounts health-care policy-sensitive names", {
      impact: -2.5,
    }),
    edge("sp500", "healthcare-etf", "Broad risk appetite transmits into the defensive sector", {
      beta: 0.62,
    }),
  ],
  summary: {
    headline: "The House outcome rests on suburban turnout and inflation, while the market effect is more sector-specific than index-wide.",
    mainUncertainty: "Whether late inflation changes the national vote enough to outweigh candidate quality.",
    followUps: ["Competitive-district polling", "October employment report", "Three-month annualized CPI"],
  },
};
