import { LlmGraph } from "@/lib/schema";
import type { z } from "zod";

type LlmEdge = z.infer<typeof LlmGraph>["edges"][number];

const edge = (
  source: string,
  target: string,
  mechanism: string,
  options: Partial<Omit<LlmEdge, "source" | "target" | "mechanism">> = {},
): LlmEdge => ({
  source,
  target,
  mechanism,
  assumptions: options.assumptions ?? [],
  confidence: options.confidence ?? "medium",
  sourceIds: options.sourceIds ?? [],
  polarity: options.polarity ?? null,
  strength: options.strength ?? null,
  impact: options.impact ?? null,
  beta: options.beta ?? null,
  threshold: options.threshold ?? null,
  direction: options.direction ?? null,
  width: options.width ?? null,
});

export const seed: z.infer<typeof LlmGraph> = {
  nodes: [
    {
      id: "photonics-accelerates",
      kind: "event",
      statement: "Photonic interconnects are adopted in datacenters faster than expected",
      resolution: "Two hyperscalers disclose production deployments of photonic interconnects",
      base: 0.25,
      lagDays: [90, 365],
      rationale: "AI cluster power density makes electrical reach and SerDes power a binding design constraint.",
      analogs: ["400G and 800G optical transceiver adoption"],
      assumptions: ["AI cluster build-outs remain capital intensive"],
      confidence: "medium",
      marketQuery: "hyperscaler photonic interconnect production deployment",
      isRoot: true,
      isTarget: false,
    },
    {
      id: "co-packaged-optics-win",
      kind: "event",
      statement: "A co-packaged optics design wins a production AI-network slot",
      resolution: "A supplier names a production co-packaged optics program with shipment timing",
      base: 0.3,
      lagDays: [90, 300],
      rationale: "A named production win turns optical interconnect demand from a lab roadmap into a bill-of-materials pull.",
      analogs: ["Early 800G design-win disclosures"],
      assumptions: ["The customer does not revert to pluggable optics at qualification"],
      confidence: "low",
      marketQuery: "co-packaged optics production design win",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "switch-asic-power-wall",
      kind: "event",
      statement: "Switch ASIC power consumption breaches rack thermal design targets",
      resolution: "A hyperscaler technical disclosure reports a power or thermal limit requiring optical redesign",
      base: 0.46,
      lagDays: [30, 240],
      rationale: "Electrical I/O power rises rapidly at higher speeds and creates a direct incentive for optical links closer to the ASIC.",
      analogs: ["51.2T switch thermal constraints"],
      assumptions: ["Power is a higher priority than component-cost minimization"],
      confidence: "medium",
      marketQuery: "switch ASIC power thermal limit co packaged optics",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "hyperscaler-capex",
      kind: "event",
      statement: "Hyperscaler AI datacenter capex remains above guidance",
      resolution: "Two major hyperscalers raise annual AI infrastructure capex guidance",
      base: 0.58,
      lagDays: [0, 180],
      rationale: "Higher cluster deployment volumes shorten the time needed to justify new interconnect architectures.",
      analogs: ["2023 to 2025 AI capex revisions"],
      assumptions: ["GPU supply remains available enough to deploy new clusters"],
      confidence: "high",
      marketQuery: "hyperscaler AI datacenter capex guidance",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "packaging-yield-delay",
      kind: "event",
      statement: "Advanced packaging yields delay photonic module qualification",
      resolution: "A supplier delays a planned volume-ramp date by at least one quarter for yield reasons",
      base: 0.36,
      lagDays: [60, 270],
      rationale: "Thermal alignment and heterogeneous integration can convert a design win into a slower revenue ramp.",
      analogs: ["Silicon photonics packaging yield ramps"],
      assumptions: ["Alternative packaging houses cannot qualify quickly"],
      confidence: "medium",
      marketQuery: "silicon photonics packaging yield delay",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "interoperability-standard",
      kind: "event",
      statement: "An open optical-interconnect standard gains multi-vendor support",
      resolution: "Three major networking vendors announce compatible products or a formal standards profile",
      base: 0.4,
      lagDays: [90, 300],
      rationale: "Interoperability lowers the procurement risk of adopting an interconnect architecture early.",
      analogs: ["OIF and Ethernet optical standards"],
      assumptions: ["Standards work maps to purchasable modules rather than a long research process"],
      confidence: "low",
      marketQuery: "open optical interconnect standard multi vendor",
      isRoot: false,
      isTarget: false,
    },
    {
      id: "coherent",
      kind: "numeric",
      name: "Coherent Corp",
      unit: "USD/share",
      ticker: "COHR",
      current: 95,
      baselineMove: 0,
      sigma: 28,
      rationale: "Coherent has exposure to optical components and datacenter interconnect demand.",
      assumptions: ["Datacenter optical mix matters more than legacy industrial demand"],
      confidence: "medium",
    },
    {
      id: "lumentum",
      kind: "numeric",
      name: "Lumentum Holdings",
      unit: "USD/share",
      ticker: "LITE",
      current: 75,
      baselineMove: 0,
      sigma: 30,
      rationale: "Lumentum is a liquid optical-component proxy with leverage to higher-speed transceiver demand.",
      assumptions: ["Inventory digestion does not dominate the optical demand cycle"],
      confidence: "medium",
    },
  ],
  edges: [
    edge("switch-asic-power-wall", "photonics-accelerates", "Power and thermal constraints increase the value of optical I/O", {
      polarity: "promote",
      strength: 0.48,
    }),
    edge("hyperscaler-capex", "photonics-accelerates", "More AI clusters justify earlier architecture transitions", {
      polarity: "promote",
      strength: 0.44,
      confidence: "high",
    }),
    edge("interoperability-standard", "photonics-accelerates", "Multi-vendor support reduces procurement and lock-in risk", {
      polarity: "promote",
      strength: 0.4,
    }),
    edge("photonics-accelerates", "co-packaged-optics-win", "Faster adoption makes a production design win more likely", {
      polarity: "promote",
      strength: 0.66,
    }),
    edge("packaging-yield-delay", "co-packaged-optics-win", "Yield delays postpone qualification and volume shipments", {
      polarity: "inhibit",
      strength: 0.58,
      confidence: "high",
    }),
    edge("photonics-accelerates", "coherent", "Faster optical deployment lifts datacenter component demand", {
      impact: 18,
    }),
    edge("co-packaged-optics-win", "coherent", "A named program validates incremental component revenue", {
      impact: 12,
    }),
    edge("packaging-yield-delay", "coherent", "Delayed qualification defers the expected revenue ramp", {
      impact: -8,
    }),
    edge("photonics-accelerates", "lumentum", "Higher-speed optical links increase demand for optical components", {
      impact: 14,
    }),
    edge("coherent", "lumentum", "Optical-component peers share part of the same demand cycle", {
      beta: 0.55,
    }),
  ],
  summary: {
    headline: "Power constraints and capex can pull photonics forward, but packaging yield remains the gate on a production ramp.",
    mainUncertainty: "Whether co-packaged optics clears qualification before pluggable optics improve enough to defer adoption.",
    followUps: ["Hyperscaler network architecture disclosures", "Supplier production design wins", "Advanced packaging yield commentary"],
  },
};
